

all:
	cd HW1 && make
	cd HW2 && make
	cd HW3 && make
	cd HW4 && make
	cd HW5 && make
	
clean:
	cd HW1 && make clean
	cd HW2 && make clean
	cd HW3 && make clean
	cd HW4 && make clean
	cd HW5 && make clean
		
