#ifndef __Medical SupplyMyDialog2__
#define __Medical SupplyMyDialog2__

/**
@file
Subclass of MyDialog2, which is generated by wxFormBuilder.
*/

#include "med.h"

/** Implementing MyDialog2 */
class Medical SupplyMyDialog2 : public MyDialog2
{
public:
	/** Constructor */
	Medical SupplyMyDialog2( wxWindow* parent );
};

#endif // __Medical SupplyMyDialog2__
