#ifndef __Medical SupplyMedMain__
#define __Medical SupplyMedMain__

/**
@file
Subclass of MedMain, which is generated by wxFormBuilder.
*/

#include "med.h"

/** Implementing MedMain */
class Medical SupplyMedMain : public MedMain
{
public:
	/** Constructor */
	Medical SupplyMedMain( wxWindow* parent );
};

#endif // __Medical SupplyMedMain__
