#ifndef __Medical SupplyDefectPanel__
#define __Medical SupplyDefectPanel__

/**
@file
Subclass of DefectPanel, which is generated by wxFormBuilder.
*/

#include "med.h"

/** Implementing DefectPanel */
class Medical SupplyDefectPanel : public DefectPanel
{
public:
	/** Constructor */
	Medical SupplyDefectPanel( wxWindow* parent );
};

#endif // __Medical SupplyDefectPanel__
