#ifndef __Medical SupplyMyDialog21__
#define __Medical SupplyMyDialog21__

/**
@file
Subclass of MyDialog21, which is generated by wxFormBuilder.
*/

#include "med.h"

/** Implementing MyDialog21 */
class Medical SupplyMyDialog21 : public MyDialog21
{
public:
	/** Constructor */
	Medical SupplyMyDialog21( wxWindow* parent );
};

#endif // __Medical SupplyMyDialog21__
