#ifndef __MedMyDialog21__
#define __MedMyDialog21__

/**
@file
Subclass of MyDialog21, which is generated by wxFormBuilder.
*/

#include "med.h"

/** Implementing MyDialog21 */
class MedMyDialog21 : public MyDialog21
{
public:
	/** Constructor */
	MedMyDialog21( wxWindow* parent );
};

#endif // __MedMyDialog21__
