#ifndef __MedMedMain__
#define __MedMedMain__

/**
@file
Subclass of MedMain, which is generated by wxFormBuilder.
*/

#include "med.h"

/** Implementing MedMain */
class MedMedMain : public MedMain
{
public:
	/** Constructor */
	MedMedMain( wxWindow* parent );
};

#endif // __MedMedMain__
